Fix prepare.sh and fail workflow if prepare.sh fails

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -15,6 +15,10 @@ jobs:
       - name: Regenerate examples
         run: |
           sh ./examples/prepare.sh
+          if [ $? -ne 0 ]; then
+            echo "Failed to regenerate examples"
+            exit 1
+          fi
 
       - name: Diff examples
         run: |
