Splitting up shell job to see if this rectifies job cancels

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,10 +19,10 @@ jobs:
           ./run-tests.sh -Di386 test || exit 1
           ./run-tests.sh -Di386 clean || true
 
-  shell-test:
-    strategy:
-      matrix:
-        shells: [bash, ksh, dash, zsh, yash, ash, mksh]
+  shell-test-1: # First shell test job
+    # strategy:
+    #   matrix:
+    #     shells: [bash, zsh, yash, ash]
     runs-on: ubuntu-latest
 
     steps:
@@ -32,15 +32,62 @@ jobs:
       - name: Install shell
         run: |
           sudo apt-get update
-          sudo apt-get install -y ${{ matrix.shells }}
+          sudo apt-get install -y bash zsh yash ash
 
       - name: Run shell tests
         run: |
-          echo "Running tests with ${{ matrix.shells }}"
-          set -e
+          set +e
           chmod +x run-tests.sh
-          ${{ matrix.shells }} ./run-tests.sh -Dsh test || exit 1
-          ${{ matrix.shells }} ./run-tests.sh -Dsh clean || true
+          shells=("bash" "zsh" "yash" "ash")
+          failures=0
+          for shell in "${shells[@]}"; do
+            $shell ./run-tests.sh -Dsh test
+            status=$?
+            if [ $status -ne 0 ]; then
+              echo "Test failed with $shell"
+              failures=$((failures+1))
+            fi
+            $shell ./run-tests.sh -Dsh clean || true
+          done
+          if [ $failures -ne 0 ]; then
+            echo "$failures shell tests failed"
+            exit 1
+          fi
+
+  shell-test-2: # Second shell test job
+    # strategy:
+    #   matrix:
+    #     shells: [ksh, dash, mksh]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Install shell
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ksh dash mksh
+
+      - name: Run shell tests
+        run: |
+          set +e
+          chmod +x run-tests.sh
+          shells=("ksh" "dash" "mksh")
+          failures=0
+          for shell in "${shells[@]}"; do
+            $shell ./run-tests.sh -Dsh test
+            status=$?
+            if [ $status -ne 0 ]; then
+              echo "Test failed with $shell"
+              failures=$((failures+1))
+            fi
+            $shell ./run-tests.sh -Dsh clean || true
+          done
+          if [ $failures -ne 0 ]; then
+            echo "$failures shell tests failed"
+            exit 1
+          fi
 
   bootstraps:
     runs-on: ubuntu-latest
@@ -66,7 +113,7 @@ jobs:
 
   success-message:
     runs-on: ubuntu-latest
-    needs: [x86-test, shell-test, bootstraps]
+    needs: [x86-test, shell-test-1, shell-test-2, bootstraps]
     steps:
       - name: Tests finished
         run: |
